### PR TITLE
controls for export, des, aNULL, eNULL ciphers + md5 mac

### PR DESCRIPTION
**Pull request by supergicko**
hi,

first of all thank you for the inspec project and your open source profiles 👍 🥇 

i added controls for the [Mandatory discards](https://wiki.mozilla.org/Security/Server_Side_TLS#Mandatory_discards) to my fork. Maybe you would like to have them also here.

Cheers

### CODE REVIEW

**Comment by atomic111** [comment]
@supergicko great work. Thank you! Can you please rebase your pr.

**Comment by supergicko** [comment]
@atomic111 i think its done

**Comment by supergicko** [comment]
@atomic111 any updates?

**Comment by atomic111** [comment]
@supergicko sorry for the late response. i added the travis and other common files to the repo. can you please rebase your pr. then you should get a green ligth

**Comment by supergicko** [comment]
@atomic111 done, think we are good to go 👍  🎉

**Comment by atomic111** [comment]
@supergicko perfect, great, thank you for your work

**Pull request merged**
